---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: test
        run: go test -race ./...
      - name: lint
        uses: reviewdog/action-golangci-lint@v1
